import type { FieldDef } from "@/features/default-rules/types";

export const ALL_FIELD_DEFS: Record<string, FieldDef> = {
  经营站点: { key: "经营站点", label: "经营站点", type: "select", options: ["美国站"], layer: "uniform", group: "经营配置" },
  发货仓: { key: "发货仓", label: "发货仓", type: "select", options: ["美国-饰品"], layer: "uniform", group: "经营配置" },
  运费模版: { key: "运费模版", label: "运费模版", type: "text", hint: "按站点自动切换", layer: "uniform", group: "经营配置" },
  承诺发货时效: { key: "承诺发货时效", label: "承诺发货时效", type: "select", options: ["2个工作日内发货", "3个工作日内发货", "5个工作日内发货", "7个工作日内发货"], layer: "uniform", group: "经营配置" },
  素材语言: { key: "素材语言", label: "素材语言", type: "select", options: ["英语", "英语+德语", "英语+法语", "英语+西班牙语", "多语言"], layer: "uniform", group: "经营配置" },
  商品产地: { key: "商品产地", label: "商品产地", type: "select", options: ["中国", "美国", "日本", "韩国", "英国"], layer: "uniform", group: "商品与SKU默认" },
  产地省份: { key: "产地省份", label: "产地省份", type: "text", hint: "默认广东省", layer: "uniform", group: "商品与SKU默认" },
  商品层级: { key: "商品层级", label: "商品层级", type: "select", options: ["根据 SKU 自动判断", "单SKU商品", "多SKU商品"], layer: "uniform", group: "商品与SKU默认" },
  SPU货号规则: { key: "SPU货号规则", label: "SPU货号规则", type: "select", options: ["自动生成", "手动填写"], layer: "uniform", group: "商品与SKU默认" },
  SKU货号规则: { key: "SKU货号规则", label: "SKU货号规则", type: "select", options: ["自动生成", "手动填写"], layer: "uniform", group: "商品与SKU默认" },
  默认规格类型: { key: "默认规格类型", label: "默认规格类型", type: "text", hint: "例如：款式/颜色", layer: "uniform", group: "商品与SKU默认" },
  币种: { key: "币种", label: "币种", type: "select", options: ["CNY", "USD", "EUR", "GBP"], layer: "uniform", group: "商品与SKU默认" },
  发货仓1: { key: "发货仓1", label: "发货仓1", type: "text", hint: "默认同顶部发货仓", layer: "uniform", group: "商品与SKU默认" },
  默认库存: { key: "默认库存", label: "默认库存", type: "number", hint: "每个SKU默认数量", layer: "uniform", group: "商品与SKU默认" },
  SKU分类: { key: "SKU分类", label: "SKU分类", type: "select", options: ["单品", "同款多件装", "混合套装"], layer: "uniform", group: "商品与SKU默认" },
  SKU数量: { key: "SKU数量", label: "SKU数量", type: "number", layer: "uniform", group: "商品与SKU默认" },
  SKU数量单位: { key: "SKU数量单位", label: "SKU数量单位", type: "select", options: ["件", "套", "对", "个", "组", "盒", "袋"], layer: "uniform", group: "商品与SKU默认" },
  是否独立包装: { key: "是否独立包装", label: "是否独立包装", type: "select", options: ["是", "否"], layer: "uniform", group: "商品与SKU默认" },
  商品编码类型: { key: "商品编码类型", label: "商品编码类型", type: "select", options: ["", "UPC", "EAN", "GTIN", "ASIN", "ISBN"], hint: "选填", layer: "uniform", group: "商品与SKU默认" },
  商品编码: { key: "商品编码", label: "商品编码", type: "text", hint: "选填", layer: "uniform", group: "商品与SKU默认" },
  制造商建议零售价USD: { key: "制造商建议零售价(USD)", label: "建议零售价(USD)", type: "text", hint: "非必填", layer: "uniform", group: "商品与SKU默认" },
  参考链接: { key: "参考链接", label: "参考链接", type: "text", hint: "选填，获取申报参考价", layer: "uniform", group: "商品与SKU默认" },
  最长边cm: { key: "最长边（cm）", label: "最长边(cm)", type: "number", hint: "cm", layer: "uniform", group: "尺寸与重量" },
  次长边cm: { key: "次长边（cm）", label: "次长边(cm)", type: "number", hint: "cm", layer: "uniform", group: "尺寸与重量" },
  最短边cm: { key: "最短边（cm）", label: "最短边(cm)", type: "number", hint: "cm", layer: "uniform", group: "尺寸与重量" },
  重量g: { key: "重量（g）", label: "重量(g)", type: "number", hint: "克", layer: "uniform", group: "尺寸与重量" },
  敏感词属性1: { key: "敏感词属性1", label: "敏感词属性1", type: "select", options: ["", "纯电", "内电", "液体", "粉末", "膏体", "刀具", "磁性", "气雾剂"], hint: "无敏感则空", layer: "uniform", group: "敏感属性" },
  敏感词属性2: { key: "敏感词属性2", label: "敏感词属性2", type: "select", options: ["", "纯电", "内电", "液体", "粉末", "膏体", "刀具", "磁性", "气雾剂"], layer: "uniform", group: "敏感属性" },
  敏感词属性3: { key: "敏感词属性3", label: "敏感词属性3", type: "select", options: ["", "纯电", "内电", "液体", "粉末", "膏体", "刀具", "磁性", "气雾剂"], layer: "uniform", group: "敏感属性" },
  液体容量ml: { key: "液体容量（ml）", label: "液体容量(ml)", type: "text", hint: "选择液体时填", layer: "uniform", group: "敏感属性" },
  刀具长度cm: { key: "刀具长度(cm)", label: "刀具长度(cm)", type: "text", hint: "选择刀具时填", layer: "uniform", group: "敏感属性" },
  刀尖角度度: { key: "刀尖角度(度)", label: "刀尖角度(度)", type: "text", hint: "选择刀具时填", layer: "uniform", group: "敏感属性" },
  储电容量wh: { key: "储电容量（wh）", label: "储电容量(wh)", type: "text", hint: "选择纯电/内电时填", layer: "uniform", group: "敏感属性" },
  镀层: { key: "镀层", label: "镀层", type: "select", options: ["无镀层", "镀金", "镀银", "镀铜", "镀玫瑰金", "镀白金"], layer: "category", group: "类目属性" },
  镶嵌材质: { key: "镶嵌材质", label: "镶嵌材质", type: "select", options: ["无镶嵌", "锆石", "珍珠", "宝石", "水钻", "翡翠", "珊瑚"], layer: "category", group: "类目属性" },
  主体材质: { key: "主体材质", label: "主体材质", type: "select", options: ["合金", "纯银", "925银", "不锈钢", "钛钢", "铜", "木头", "树脂"], layer: "category", group: "类目属性" },
  银材料净克重: { key: "银材料净克重(g）", label: "银材料净克重(g）", type: "text", hint: "银材质时必填", layer: "category", group: "类目属性" },
  银材料净克重单位: { key: "银材料净克重(g）单位", label: "银材料净克重单位", type: "select", options: ["g", "mg"], layer: "category", group: "类目属性" },
  耳针材质: { key: "耳针材质", label: "耳针材质", type: "select", options: ["合金", "纯银", "925银", "不锈钢", "钛钢"], layer: "category", group: "类目属性" },
  是否为羽毛: { key: "是否为羽毛", label: "是否为羽毛", type: "select", options: ["否", "是"], layer: "category", group: "类目属性" },
  适配季节: { key: "适配季节", label: "适配季节", type: "select", options: ["四季", "春季", "夏季", "秋季", "冬季", "春夏", "秋冬"], layer: "category", group: "类目属性" },
  是否含金属部件: { key: "是否含金属部件", label: "是否含金属部件", type: "select", options: ["是", "否"], layer: "category", group: "类目属性" },
  金属部件材质类型1: { key: "金属部件材质类型1", label: "金属部件材质类型1", type: "select", options: ["合金", "纯银", "925银", "不锈钢", "钛钢", "铜"], layer: "category", group: "类目属性" },
  金属部件材质类型2: { key: "金属部件材质类型2", label: "金属部件材质类型2", type: "select", options: ["", "合金", "纯银", "925银", "不锈钢", "钛钢", "铜"], layer: "category", group: "类目属性" },
  金属部件材质类型3: { key: "金属部件材质类型3", label: "金属部件材质类型3", type: "select", options: ["", "合金", "纯银", "925银", "不锈钢", "钛钢", "铜"], layer: "category", group: "类目属性" },
  木材类型: { key: "木材类型", label: "木材类型", type: "text", hint: "木质饰品填写", layer: "category", group: "类目属性" },
  木种: { key: "木种", label: "木种", type: "text", hint: "例如：红木、松木", layer: "category", group: "类目属性" },
  羽毛材质: { key: "羽毛材质", label: "羽毛材质", type: "text", hint: "羽毛饰品填写", layer: "category", group: "类目属性" },
  风格1: { key: "风格1", label: "风格1（可选）", type: "textarea", hint: "例如：时尚、简约、复古", layer: "category", group: "风格与场合" },
  风格2: { key: "风格2", label: "风格2（可选）", type: "textarea", layer: "category", group: "风格与场合" },
  风格3: { key: "风格3", label: "风格3（可选）", type: "textarea", layer: "category", group: "风格与场合" },
  佩戴场合1: { key: "佩戴场合1", label: "佩戴场合1（可选）", type: "textarea", hint: "例如：日常、派对", layer: "category", group: "风格与场合" },
  佩戴场合2: { key: "佩戴场合2", label: "佩戴场合2（可选）", type: "textarea", layer: "category", group: "风格与场合" },
  营销节日1: { key: "营销节日1", label: "营销节日1（可选）", type: "textarea", hint: "例如：情人节、圣诞节", layer: "category", group: "风格与场合" },
  主题1: { key: "主题1", label: "主题1（可选）", type: "textarea", hint: "例如：几何、花朵、爱心", layer: "category", group: "风格与场合" },
  诞生石1: { key: "诞生石1", label: "诞生石1（可选）", type: "textarea", layer: "category", group: "风格与场合" },
  系列线1: { key: "系列线1", label: "系列线1（可选）", type: "textarea", layer: "category", group: "风格与场合" },
  申报价格美国站: { key: "申报价格-美国站", label: "申报价格（美国站）", type: "text", hint: "必填，需参考同类商品价格", layer: "manual", group: "人工必填" },
};

export const FIELD_GROUPS_ORDER = ["经营配置", "商品与SKU默认", "尺寸与重量", "敏感属性", "类目属性", "风格与场合", "人工必填"];

export function getGroupFields(group: string): FieldDef[] {
  return Object.values(ALL_FIELD_DEFS).filter((f) => f.group === group);
}
